package com.lifedawn.capstoneapp.map;

public enum BottomSheetType {
	SEARCH_LOCATION, BUILDING, INSTANCE_INFO, WEATHER, RESTAURANT, LOCATION_ITEM, SELECTED_PLACE_CATEGORY, FAVORITE_LOCATIONS,
	SELECTED_LOCATION_INFO, AROUND_PLACES, FIND_ROUTES
}